# ==================================================
# Application
# ==================================================
spring.application.name=operion-api

# ==================================================
# Database
# ==================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ==================================================
# JPA / Hibernate
# ==================================================
spring.jpa.hibernate.ddl-auto=validate

# Optional: Explicitly specify the Hibernate dialect
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==================================================
# Flyway
# ==================================================
spring.flyway.enabled=true

# ==================================================
# Security
# ==================================================
logging.level.org.springframework.security=DEBUG

# ==================================================
# JWT
# ==================================================
jwt.secret=${JWT_SECRET}